["Kerer큰"]
skip = false
ignored_patterns = [
  "Kereru-?Symes",
  "Te Kereru",
  "Kereru School",
  "Kereru Publishing",
  "Kereru Park",
  "Kereru Numia",
  "Kereru Geyser",
  "Kereru Lane",
  "Kereru Brewing",
  "\\[\\[Kereru \\(place\\)\\|Kereru\\]\\]",
  "File:Kereru",
  "Image:Kereru",
  "Numai Kereru",
  "Tipapa-Kereru",
  "kererudiscovery",
  "Kereru[- ]crowned",
  "Kereru Homestead",
  "image[0-9]? = Kereru",
  "title=Kereru",
]
ignored_pages = [
  "Rosehill, New Zealand", # Citations.
  "List of villages in Ogun State",
  "K훮k훮",
  "Aristotelia serrata",
  "Kerer큰",
  "Flower",
  "Panaruawhiti / Endeavour Inlet",
]
